title: Humanities Data Inquiry
email: nathan.woods@uleth.ca
description: >-
  Website of the Humanities Data Inquiry Project, hosted by the University of Lethbridge Humanities Innovation Lab.

baseurl: "/hdi-demo-personal"
url: "https://tessabordalejo.github.io"

github_username: tessabordalejo

plugins:
  - jekyll-feed
